# Generated by Django 3.1.5 on 2021-01-28 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_component'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='component',
            options={'ordering': ['name']},
        ),
    ]
