# Generated by Django 3.1.5 on 2021-01-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20210128_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name_plural': 'services'},
        ),
        migrations.AlterField(
            model_name='component',
            name='services',
            field=models.ManyToManyField(related_name='services', to='services.Service'),
        ),
    ]
