# Generated by Django 3.1.5 on 2021-01-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20210128_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='services',
            field=models.ManyToManyField(to='services.Service'),
        ),
    ]
