# Generated by Django 3.1.5 on 2021-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20210128_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='author_lnk',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='cc_license',
            field=models.CharField(default='cc', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='cc_license_lnk',
            field=models.CharField(default='cc_link', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='component',
            name='image_author',
            field=models.CharField(default='author', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='component',
            name='image_lnk',
            field=models.CharField(default='link', max_length=200),
            preserve_default=False,
        ),
    ]
