# Generated by Django 3.1.5 on 2021-01-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210127_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type_of_service',
            field=models.CharField(choices=[], max_length=80),
        ),
    ]
