# Generated by Django 3.1.5 on 2021-01-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210128_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type_of_service',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Software Maintenance and Admin', 'Software Maintenance and Admin'), ('Tuition', 'Tuition'), ('Hardware Maintenance and Upgrades', 'Hardware Maintenance and Upgrades'), ('Cloud Based Web Development', 'Cloud Based Web Development'), ('IT Support and Mentoring', 'IT Support and Mentoring')], max_length=80),
        ),
    ]
