# Generated by Django 3.1.5 on 2021-05-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210216_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='type_of_service',
            field=models.CharField(choices=[('IT Support and Mentoring', 'IT Support and Mentoring'), ('Tuition', 'Tuition'), ('Cloud Based Web Development', 'Cloud Based Web Development'), ('Web Development', 'Web Development'), ('Hardware Maintenance and Upgrades', 'Hardware Maintenance and Upgrades'), ('Mobile App Development', 'Mobile App Development'), ('Website Maintenance and Admin', 'Website Maintenance and Admin')], max_length=80),
        ),
    ]
